### ISSUE TITLE
Arc improvements failing Development suite

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#279] opened 2017-11-02 23:35 UTC
I believe the new modifications to arc line finding
has had unintended consequences.

The Kast_red tests are now failing in the Development suite.
You can short-cut the issue by going into the Kast_red/600_7500_d55
folder and running

```
run_pypit kast_red_600_7500_d55.pypit -d
```

it should fail like this:

  File "/home/xavier/local/Python/PYPIT/pypit/pypit.py", line 237, in PYPIT
    status = armlsd.ARMLSD(fitsdict)
  File "/home/xavier/local/Python/PYPIT/pypit/armlsd.py", line 158, in ARMLSD
    update = slf.MasterWaveCalib(fitsdict, sc, det)
  File "/home/xavier/local/Python/PYPIT/pypit/arsciexp.py", line 683, in MasterWaveCalib
    wv_calib = ararc.simple_calib(self, det)
  File "/home/xavier/local/Python/PYPIT/pypit/ararc.py", line 397, in simple_calib
    dpix_obs[kk,:] = np.array(tcent[idx] - tcent[idx_str])
ValueError: could not broadcast input array from shape (3) into shape (13)

**Comment by rcooke-ast** [comment] 2017-11-03 09:50
This is fixed in the HIRES branch. The problem is in the settings file. I'm still crashing on LRISr though, even when feeding in some lines... more to come soon

**Comment by rcooke-ast** [comment] 2017-11-03 22:26
Found a bug in the arcparams setup for LRISr. Now fixed in the `hires_optimal` branch. However, the development suite is failing when using arclines on LRISr (however, using the `simple` method works just fine, even if you don't provide a list of manual ID lines). Although, I can't figure out where the default setting (`arc calibrate method simple`) is changing to the `arc calibrate method arclines` approach. Any ideas @profxj?

**Comment by profxj** [comment] 2017-11-04 12:31
Hi @rcooke-ast --  Have tried to run on LRISr in the observatories_v2 branch of the Development
and hires_optimal and immediately fail:

beast> run_pypit keck_lris_red_2017-Nov-04.pypit  -d
[INFO]    :: pypit.py 317 load_input() - Loading the input file
[INFO]    :: pypit.py 435 load_input() - Found 23 raw data frames
[INFO]    :: pypit.py 436 load_input() - Input file loaded successfully
[INFO]    :: pypit.py 109 PYPIT() - Reducing data from the keck_lris_red spectrograph

[ERROR]   :: pypit.py 122 PYPIT() - The following instrument settings file cannot be found:
             /home/xavier/local/Python/PYPIT/pypit/data/settings/settings.keck_lris_red
             Please check the settings file exists, and that the instrument name is spelt correctly.

Please advise.

**Comment by rcooke-ast** [comment] 2017-11-04 14:05
Hmmm... it seems if want to add this functionality, we need to rename all settings files to be prefixed with the observatory name. This may not be such a bad thing, since there are some instruments that have the same name.

Are you opposed to this?

**Comment by rcooke-ast** [comment] 2017-11-04 15:00
I decided prefixed the names of all settings files with the observatory... See branches `hires_optimal` and `observatories_v2`. For some reason, there are a few crashes on the b-spline algorithm. I'll look into it...

**Comment by rcooke-ast** [comment] 2017-11-19 21:44
Addressed by PR #282

**Closed by rcooke-ast** 2017-11-19 21:45 UTC
